# -*- coding: utf-8 -*-
"""Brain Tumor detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hLaBWqmGGEr3d7xDvBt8K_dSKx_c-q94
"""

!pip install -q git+https://github.com/THU-MIG/yolov10.git

!wget -P -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt

!pip install -q roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="2BYlQZ5VtWMBnUIEPTsE")
project = rf.workspace("brain-mri").project("mri-rskcu")
version = project.version(3)
dataset = version.download("yolov9")

!yolo task=detect mode=train epochs = 25 batch=32 plots=True \
model = '/content/-q/yolov10n.pt' \
data = '/content/MRI-3/data.yaml'

from ultralytics import YOLOv10
model_path = "/content/runs/detect/train5/weights/best.pt"
model = YOLOv10(model_path)

result = model(source = "/content/MRI-3/valid/images", conf = 0.25, save=True )

import glob
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

images = glob.glob("/content/runs/detect/predict2/*.jpg")

images_to_display = images[:10]

fig, axes = plt.subplots(2,5, figsize=(20,10))

for i, ax in enumerate(axes.flat):
  if i < len(images_to_display):
    img = mpimg.imread(images_to_display[i])
    ax.imshow(img)
    ax.axis('off')
  else:
    ax.axis('off')
plt.tight_layout()
plt.show()

result = model.predict(source = "/content/MRI-3/valid/images/Tr-glTr_0000_jpg.rf.ee4ad3ca5d0eafd1f482988b89457634.jpg", imgsz = 640, conf = 0.25)
annotated_img = result[0].plot()
annotated_img[:, :, ::-1]

!pip install gradio

import gradio as gr
import cv2
import numpy as np

def predict(image):
  result = model.predict(source=image, imgsz = 640, conf = 0.25)
  annotated_img = result[0].plot()
  annotated_img = annotated_img[:, :, ::-1]
  return annotated_img

app = gr.Interface(
    fn =predict,
    inputs = gr.Image(type="numpy", label="Upload an image"),
    outputs = gr.Image(type="numpy", label="Detect Brain Tumor"),
    title = "Brain Tumor Detection Using Yolov10",
    description="Upload an image and the yolov10 model will detect and annotated brain tumor"
)

app.launch()

